name: Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Branche principale où vous travaillez

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx sphinx_rtd_theme sphinx-gallery sphinx-math-dollar
          pip install -e .

      - name: check where we are
        run: |
          pwd & ls
          ls test/
          ls runner/work/Demeter_metamorphosis/
          ls runner/work/Demeter_metamorphosis/Demeter_metamorphosis/
          

      - name: Build documentation
        run: |
          sphinx-apidoc -o docs/source/ src/demeter
          sphinx-build -b html docs/source/ docs/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build  # Dossier généré par Sphinx
